# Generated by Django 4.2.19 on 2025-02-07 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={},
        ),
    ]
