# Generated by Django 4.2.19 on 2025-02-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0002_alter_contactus_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name_plural": "Contact Us"},
        ),
    ]
