# Generated by Django 4.2.19 on 2025-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0003_alter_contactus_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="problem",
            field=models.TextField(),
        ),
    ]
