# Generated by Django 4.2.19 on 2025-02-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="available_time",
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_time",
            field=models.ManyToManyField(to="doctor.availabletime"),
        ),
    ]
